### ISSUE TITLE
The 'caldis_CA' looks like don't work

### ISSUE THREAD

**Issue by demainchen** [biomed-AI/GraphPPIS#1]
When I try to Run
import os
os.system("/Users/demainchen/Desktop/PPI-SITE/code/embedding/feature_extraction/caldis_CA"  "/Users/demainchen/Desktop/PPI-SITE/code/embedding/feature_extraction/pdb_data/3mcbB > abc.map")
print("1")

with open('/Users/demainchen/Desktop/PPI-SITE/code/embedding/abc.map', "r") as f:
        lines = f.readlines()
lines

I find the result of the terminal command line is '[]'. 
Could you please fix this problem or tell me what should I do?

**Comment by onlyonewater** [comment]
3mcbB should be a pdb-style file, it should be the 3mcbB.pdb

**Comment by YidongSong** [comment]
I have tested the 'caldis_CA' and it just works! Maybe you can check the permission of 'caldis_CA'.

**Comment by yuanqm55** [comment]
> When I try to Run import os os.system("/Users/demainchen/Desktop/PPI-SITE/code/embedding/feature_extraction/caldis_CA" "/Users/demainchen/Desktop/PPI-SITE/code/embedding/feature_extraction/pdb_data/3mcbB > abc.map") print("1")
> 
> with open('/Users/demainchen/Desktop/PPI-SITE/code/embedding/abc.map', "r") as f: lines = f.readlines() lines
> 
> I find the result of the terminal command line is '[]'. Could you please fix this problem or tell me what should I do?

I am really sorry for the long delay in this reply. I saw this issue before, but I can't reproduce this bug. Now I realize that maybe you hadn't added execution permission to caldis_CA by `chmod +x caldis_CA.` I should have mentioned this in the README.
