### ISSUE TITLE
BLAST+ seems an unvaild link

### ISSUE THREAD

**Issue by chq1155** [biomed-AI/GraphPPIS#2]

**Comment by yuanqm55** [comment]
![image](https://github.com/biomed-AI/GraphPPIS/assets/34777741/4bc4beb1-5c95-4d55-802b-3e7d0b4be847)
I can access this link. Maybe check your proxy setting.

**Comment by chq1155** [comment]
So sorry about that! I have fixed it! Thanks a lot!
